-- MySQL Script generated by MySQL Workbench
-- 2016年04月24日 星期日 19时42分40秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema safelyun
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema safelyun
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safelyun` DEFAULT CHARACTER SET utf8 ;
USE `safelyun` ;

-- -----------------------------------------------------
-- Table `safelyun`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`department` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`department` (
  `departmentId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `departmentName` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`departmentId`)  COMMENT '',
  UNIQUE INDEX `departmentName_UNIQUE` (`departmentName` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`specialty` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`specialty` (
  `specialtyId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `specialtyName` VARCHAR(45) NOT NULL COMMENT '',
  `department_departmentId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`specialtyId`)  COMMENT '',
  UNIQUE INDEX `specialtyName_UNIQUE` (`specialtyName` ASC)  COMMENT '',
  INDEX `fk_specialty_department1_idx` (`department_departmentId` ASC)  COMMENT '',
  CONSTRAINT `fk_specialty_department1`
    FOREIGN KEY (`department_departmentId`)
    REFERENCES `safelyun`.`department` (`departmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`classes` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`classes` (
  `classesId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `classesName` VARCHAR(45) NOT NULL COMMENT '',
  `specialty_specialtyId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`classesId`)  COMMENT '',
  UNIQUE INDEX `classesName_UNIQUE` (`classesName` ASC)  COMMENT '',
  INDEX `fk_classes_specialty1_idx` (`specialty_specialtyId` ASC)  COMMENT '',
  CONSTRAINT `fk_classes_specialty1`
    FOREIGN KEY (`specialty_specialtyId`)
    REFERENCES `safelyun`.`specialty` (`specialtyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`datadic_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`datadic_groups` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`datadic_groups` (
  `group_code` VARCHAR(10) NOT NULL COMMENT '',
  `group_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`group_code`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`datadic_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`datadic_items` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`datadic_items` (
  `item_code` VARCHAR(10) NOT NULL COMMENT '',
  `item_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `datadic_groups_group_code` VARCHAR(3) NOT NULL COMMENT '',
  PRIMARY KEY (`item_code`)  COMMENT '',
  INDEX `fk_datadic_items_datadic_groups1_idx` (`datadic_groups_group_code` ASC)  COMMENT '',
  CONSTRAINT `fk_datadic_items_datadic_groups1`
    FOREIGN KEY (`datadic_groups_group_code`)
    REFERENCES `safelyun`.`datadic_groups` (`group_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`examswitch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`examswitch` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`examswitch` (
  `examswitchId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `switchOnOrOff` BIT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`examswitchId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`itempool`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`itempool` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`itempool` (
  `itempoolId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `itempoolQuestion` VARCHAR(300) NULL DEFAULT NULL COMMENT '',
  `A` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  `B` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  `C` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  `D` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  `itempoolCorrect` VARCHAR(1) NULL DEFAULT NULL COMMENT '',
  `itempoolChecked` BIT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`itempoolId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`menu` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`menu` (
  `menuId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `menuName` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `menuUrl` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`menuId`)  COMMENT '',
  UNIQUE INDEX `menuUrl_UNIQUE` (`menuUrl` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`role` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`role` (
  `roleId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `roleName` VARCHAR(25) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`roleId`)  COMMENT '',
  UNIQUE INDEX `roleName_UNIQUE` (`roleName` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`role_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`role_menu` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`role_menu` (
  `role_menu_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `role_roleId` INT(11) NOT NULL COMMENT '',
  `menu_menuId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`role_menu_id`)  COMMENT '',
  INDEX `fk_role_has_menu_menu1_idx` (`menu_menuId` ASC)  COMMENT '',
  INDEX `fk_role_has_menu_role1_idx` (`role_roleId` ASC)  COMMENT '',
  CONSTRAINT `fk_role_has_menu_menu1`
    FOREIGN KEY (`menu_menuId`)
    REFERENCES `safelyun`.`menu` (`menuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_menu_role1`
    FOREIGN KEY (`role_roleId`)
    REFERENCES `safelyun`.`role` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`user` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`user` (
  `userId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `userName` VARCHAR(100) NOT NULL COMMENT '',
  `userPassword` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`userId`)  COMMENT '',
  UNIQUE INDEX `id_user_UNIQUE` (`userId` ASC)  COMMENT '',
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`student` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`student` (
  `studentId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `studentNumber` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `studentName` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `grade` VARCHAR(4) NULL DEFAULT NULL COMMENT '',
  `studentSex` VARCHAR(2) NULL DEFAULT NULL COMMENT '',
  `studentEmail` VARCHAR(45) NULL DEFAULT '' COMMENT '',
  `user_userId` INT(11) NOT NULL COMMENT '',
  `classes_classesId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`studentId`)  COMMENT '',
  UNIQUE INDEX `studentNumber_UNIQUE` (`studentNumber` ASC)  COMMENT '',
  INDEX `fk_student_user1_idx` (`user_userId` ASC)  COMMENT '',
  INDEX `fk_student_classes1_idx` (`classes_classesId` ASC)  COMMENT '',
  CONSTRAINT `fk_student_classes1`
    FOREIGN KEY (`classes_classesId`)
    REFERENCES `safelyun`.`classes` (`classesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `safelyun`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`score` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`score` (
  `scoreId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `scoreMark` FLOAT NULL DEFAULT NULL COMMENT '',
  `scoreMakeupNum` INT(11) NULL DEFAULT NULL COMMENT '',
  `student_studentId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`scoreId`)  COMMENT '',
  INDEX `fk_score_student1_idx` (`student_studentId` ASC)  COMMENT '',
  CONSTRAINT `fk_score_student1`
    FOREIGN KEY (`student_studentId`)
    REFERENCES `safelyun`.`student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`section` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`section` (
  `sectionId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `sectionName` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `sectionChecked` BIT(1) NULL DEFAULT NULL COMMENT '',
  `sectionCode` INT NULL COMMENT '',
  PRIMARY KEY (`sectionId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`semester` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`semester` (
  `semesterId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `semesterName` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`semesterId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`subsection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`subsection` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`subsection` (
  `subsectionId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `subsectionName` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `subsectionContent` TEXT NULL DEFAULT NULL COMMENT '',
  `subsectionTime` INT(11) NULL DEFAULT NULL COMMENT '存储时长，只记录多少分钟',
  `subsectionChecked` BIT(1) NULL DEFAULT NULL COMMENT '',
  `subsectionCode` INT NULL COMMENT '',
  `section_sectionId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`subsectionId`)  COMMENT '',
  INDEX `fk_subsection_section1_idx` (`section_sectionId` ASC)  COMMENT '',
  CONSTRAINT `fk_subsection_section1`
    FOREIGN KEY (`section_sectionId`)
    REFERENCES `safelyun`.`section` (`sectionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`studyschedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`studyschedule` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`studyschedule` (
  `studyscheduleId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `studyscheduleHasNum` INT(11) NULL DEFAULT NULL COMMENT '',
  `subsection_subsectionId` INT(11) NOT NULL COMMENT '',
  `student_studentId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`studyscheduleId`)  COMMENT '',
  INDEX `fk_studyschedule_subsection1_idx` (`subsection_subsectionId` ASC)  COMMENT '',
  INDEX `fk_studyschedule_student1_idx` (`student_studentId` ASC)  COMMENT '',
  CONSTRAINT `fk_studyschedule_student1`
    FOREIGN KEY (`student_studentId`)
    REFERENCES `safelyun`.`student` (`studentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studyschedule_subsection1`
    FOREIGN KEY (`subsection_subsectionId`)
    REFERENCES `safelyun`.`subsection` (`subsectionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`user_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`user_classes` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`user_classes` (
  `user_classes_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_userId` INT(11) NOT NULL COMMENT '',
  `classes_classesId` INT(11) NOT NULL COMMENT '',
  `grade` VARCHAR(4) NULL COMMENT '',
  PRIMARY KEY (`user_classes_id`)  COMMENT '',
  INDEX `fk_user_has_classes_classes1_idx` (`classes_classesId` ASC)  COMMENT '',
  INDEX `fk_user_has_classes_user1_idx` (`user_userId` ASC)  COMMENT '',
  CONSTRAINT `fk_user_has_classes_classes1`
    FOREIGN KEY (`classes_classesId`)
    REFERENCES `safelyun`.`classes` (`classesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_classes_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `safelyun`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safelyun`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safelyun`.`user_role` ;

CREATE TABLE IF NOT EXISTS `safelyun`.`user_role` (
  `user_role_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `user_userId` INT(11) NOT NULL COMMENT '',
  `role_roleId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`user_role_id`)  COMMENT '',
  INDEX `fk_user_has_role_role1_idx` (`role_roleId` ASC)  COMMENT '',
  INDEX `fk_user_has_role_user1_idx` (`user_userId` ASC)  COMMENT '',
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_roleId`)
    REFERENCES `safelyun`.`role` (`roleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `safelyun`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
