package com.paly.domain;

import java.io.Serializable;

public class Classes implements Serializable {

	private static final long serialVersionUID = 4158176263435498562L;

    private Integer classesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.classesName
     *
     * @mbggenerated
     */
    private String classesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.specialty_specialtyId
     *
     * @mbggenerated
     */
    private Integer specialty_specialtyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.classesId
     *
     * @return the value of classes.classesId
     *
     * @mbggenerated
     */
    public Integer getClassesId() {
        return classesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.classesId
     *
     * @param classesId the value for classes.classesId
     *
     * @mbggenerated
     */
    public void setClassesId(Integer classesId) {
        this.classesId = classesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.classesName
     *
     * @return the value of classes.classesName
     *
     * @mbggenerated
     */
    public String getClassesName() {
        return classesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.classesName
     *
     * @param classesName the value for classes.classesName
     *
     * @mbggenerated
     */
    public void setClassesName(String classesName) {
        this.classesName = classesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.specialty_specialtyId
     *
     * @return the value of classes.specialty_specialtyId
     *
     * @mbggenerated
     */
    public Integer getSpecialty_specialtyId() {
        return specialty_specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.specialty_specialtyId
     *
     * @param specialty_specialtyId the value for classes.specialty_specialtyId
     *
     * @mbggenerated
     */
    public void setSpecialty_specialtyId(Integer specialty_specialtyId) {
        this.specialty_specialtyId = specialty_specialtyId;
    }
}