package com.paly.domain;

import java.io.Serializable;

public class Department implements Serializable {

	private static final long serialVersionUID = 4223786325279786587L;

    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.departmentName
     *
     * @mbggenerated
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.departmentId
     *
     * @return the value of department.departmentId
     *
     * @mbggenerated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.departmentId
     *
     * @param departmentId the value for department.departmentId
     *
     * @mbggenerated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.departmentName
     *
     * @return the value of department.departmentName
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.departmentName
     *
     * @param departmentName the value for department.departmentName
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
}