package com.paly.domain;

import java.io.Serializable;
import java.util.List;

/**
 * 院系
 * @author linyu
 *
 */
public class Department implements Serializable {

	private static final long serialVersionUID = 4223786325279786587L;

    private Integer departmentId;

    /**
     * 院系名
     */
    private String departmentName;
    
    /**
     * 一个院系下有多个专业
     */
    private List<Specialty> specialties;
    

    public Department() {
		super();
	}

    /**
     * 传入院系名称参数实例化院系实体
     * @param departmentName 院系名称，不能为null
     */
	public Department(String departmentName) {
		super();
		this.departmentName = departmentName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.departmentId
     *
     * @return the value of department.departmentId
     *
     * @mbggenerated
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.departmentId
     *
     * @param departmentId the value for department.departmentId
     *
     * @mbggenerated
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.departmentName
     *
     * @return the value of department.departmentName
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.departmentName
     *
     * @param departmentName the value for department.departmentName
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

	public List<Specialty> getSpecialties() {
		return specialties;
	}

	public void setSpecialties(List<Specialty> specialties) {
		this.specialties = specialties;
	}
}