package com.paly.domain;

import java.io.Serializable;

/**
 * 题库
 * @author linyu
 *
 */
public class Itempool implements Serializable {
   
	private static final long serialVersionUID = -8244518489566882905L;

    private Integer itempoolId;

    /**
     * 题目
     */
    private String itempoolQuestion;

    /**
     * A选项
     */
    private String a;

    /**
     * B选项
     */
    private String b;

    /**
     * C选项
     */
    private String c;

    /**
     * D选项
     */
    private String d;

    /**
     * 正确答案
     */
    private String itempoolCorrect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itempool.itempoolChecked
     *
     * @mbggenerated
     */
    private Boolean itempoolChecked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.itempoolId
     *
     * @return the value of itempool.itempoolId
     *
     * @mbggenerated
     */
    public Integer getItempoolId() {
        return itempoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.itempoolId
     *
     * @param itempoolId the value for itempool.itempoolId
     *
     * @mbggenerated
     */
    public void setItempoolId(Integer itempoolId) {
        this.itempoolId = itempoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.itempoolQuestion
     *
     * @return the value of itempool.itempoolQuestion
     *
     * @mbggenerated
     */
    public String getItempoolQuestion() {
        return itempoolQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.itempoolQuestion
     *
     * @param itempoolQuestion the value for itempool.itempoolQuestion
     *
     * @mbggenerated
     */
    public void setItempoolQuestion(String itempoolQuestion) {
        this.itempoolQuestion = itempoolQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.A
     *
     * @return the value of itempool.A
     *
     * @mbggenerated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.A
     *
     * @param a the value for itempool.A
     *
     * @mbggenerated
     */
    public void setA(String a) {
        this.a = a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.B
     *
     * @return the value of itempool.B
     *
     * @mbggenerated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.B
     *
     * @param b the value for itempool.B
     *
     * @mbggenerated
     */
    public void setB(String b) {
        this.b = b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.C
     *
     * @return the value of itempool.C
     *
     * @mbggenerated
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.C
     *
     * @param c the value for itempool.C
     *
     * @mbggenerated
     */
    public void setC(String c) {
        this.c = c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.D
     *
     * @return the value of itempool.D
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.D
     *
     * @param d the value for itempool.D
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.itempoolCorrect
     *
     * @return the value of itempool.itempoolCorrect
     *
     * @mbggenerated
     */
    public String getItempoolCorrect() {
        return itempoolCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.itempoolCorrect
     *
     * @param itempoolCorrect the value for itempool.itempoolCorrect
     *
     * @mbggenerated
     */
    public void setItempoolCorrect(String itempoolCorrect) {
        this.itempoolCorrect = itempoolCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itempool.itempoolChecked
     *
     * @return the value of itempool.itempoolChecked
     *
     * @mbggenerated
     */
    public Boolean getItempoolChecked() {
        return itempoolChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itempool.itempoolChecked
     *
     * @param itempoolChecked the value for itempool.itempoolChecked
     *
     * @mbggenerated
     */
    public void setItempoolChecked(Boolean itempoolChecked) {
        this.itempoolChecked = itempoolChecked;
    }
}