package com.paly.domain;

import java.io.Serializable;
import java.util.List;

/**
 * 菜单
 * @author linyu
 *
 */
public class Menu implements Serializable {
 
	private static final long serialVersionUID = 2937010482908369129L;

    private Integer menuId;

    /**
     * 菜单名
     */
    private String menuName;

    /**
     * 菜单url
     */
    private String menuUrl;    
    
    /**
     * 属于多个角色
     */
    private List<Role> roles;

    
    public Menu() {
		super();
	}
    
	public Menu(String menuName, String menuUrl) {
		this.menuName = menuName;
		this.menuUrl = menuUrl;
	}


	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuId
     *
     * @return the value of menu.menuId
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuId
     *
     * @param menuId the value for menu.menuId
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuName
     *
     * @return the value of menu.menuName
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuName
     *
     * @param menuName the value for menu.menuName
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menuUrl
     *
     * @return the value of menu.menuUrl
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menuUrl
     *
     * @param menuUrl the value for menu.menuUrl
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}
}