package com.paly.domain;

import java.io.Serializable;

public class Score implements Serializable {
   
	private static final long serialVersionUID = -7188061286119301858L;

    private Integer scoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.scoreMark
     *
     * @mbggenerated
     */
    private Byte scoreMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_studentId
     *
     * @mbggenerated
     */
    private Integer student_studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.scoreMakeupNum
     *
     * @mbggenerated
     */
    private Byte scoreMakeupNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.scoreId
     *
     * @return the value of score.scoreId
     *
     * @mbggenerated
     */
    public Integer getScoreId() {
        return scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.scoreId
     *
     * @param scoreId the value for score.scoreId
     *
     * @mbggenerated
     */
    public void setScoreId(Integer scoreId) {
        this.scoreId = scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.scoreMark
     *
     * @return the value of score.scoreMark
     *
     * @mbggenerated
     */
    public Byte getScoreMark() {
        return scoreMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.scoreMark
     *
     * @param scoreMark the value for score.scoreMark
     *
     * @mbggenerated
     */
    public void setScoreMark(Byte scoreMark) {
        this.scoreMark = scoreMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_studentId
     *
     * @return the value of score.student_studentId
     *
     * @mbggenerated
     */
    public Integer getStudent_studentId() {
        return student_studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_studentId
     *
     * @param student_studentId the value for score.student_studentId
     *
     * @mbggenerated
     */
    public void setStudent_studentId(Integer student_studentId) {
        this.student_studentId = student_studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.scoreMakeupNum
     *
     * @return the value of score.scoreMakeupNum
     *
     * @mbggenerated
     */
    public Byte getScoreMakeupNum() {
        return scoreMakeupNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.scoreMakeupNum
     *
     * @param scoreMakeupNum the value for score.scoreMakeupNum
     *
     * @mbggenerated
     */
    public void setScoreMakeupNum(Byte scoreMakeupNum) {
        this.scoreMakeupNum = scoreMakeupNum;
    }
}