package com.paly.domain;

import java.io.Serializable;

public class Section implements Serializable {
    
	private static final long serialVersionUID = -5897895452712431531L;
	
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.sectionName
     *
     * @mbggenerated
     */
    private String sectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.sectionChecked
     *
     * @mbggenerated
     */
    private Boolean sectionChecked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.sectionId
     *
     * @return the value of section.sectionId
     *
     * @mbggenerated
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.sectionId
     *
     * @param sectionId the value for section.sectionId
     *
     * @mbggenerated
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.sectionName
     *
     * @return the value of section.sectionName
     *
     * @mbggenerated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.sectionName
     *
     * @param sectionName the value for section.sectionName
     *
     * @mbggenerated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.sectionChecked
     *
     * @return the value of section.sectionChecked
     *
     * @mbggenerated
     */
    public Boolean getSectionChecked() {
        return sectionChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.sectionChecked
     *
     * @param sectionChecked the value for section.sectionChecked
     *
     * @mbggenerated
     */
    public void setSectionChecked(Boolean sectionChecked) {
        this.sectionChecked = sectionChecked;
    }
}