package com.paly.domain;

import java.io.Serializable;

/**
 * 学期
 * @author linyu
 *
 */
public class Semester implements Serializable {
   
	private static final long serialVersionUID = -1567764836508659462L;

	
    private Integer semesterId;

    /**
     * 学期名  
     */
    private String semesterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column semester.semesterId
     *
     * @return the value of semester.semesterId
     *
     * @mbggenerated
     */
    public Integer getSemesterId() {
        return semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column semester.semesterId
     *
     * @param semesterId the value for semester.semesterId
     *
     * @mbggenerated
     */
    public void setSemesterId(Integer semesterId) {
        this.semesterId = semesterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column semester.semesterName
     *
     * @return the value of semester.semesterName
     *
     * @mbggenerated
     */
    public String getSemesterName() {
        return semesterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column semester.semesterName
     *
     * @param semesterName the value for semester.semesterName
     *
     * @mbggenerated
     */
    public void setSemesterName(String semesterName) {
        this.semesterName = semesterName;
    }
}