package com.paly.domain;

import java.io.Serializable;

/**
 * 专业
 * @author linyu
 *
 */
public class Specialty implements Serializable {
   
	private static final long serialVersionUID = 8032169560857196948L;
	
    private Integer specialtyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.specialtyName
     *
     * @mbggenerated
     */
    private String specialtyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specialty.department_departmentId
     *
     * @mbggenerated
     */
    private Integer department_departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialtyId
     *
     * @return the value of specialty.specialtyId
     *
     * @mbggenerated
     */
    public Integer getSpecialtyId() {
        return specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialtyId
     *
     * @param specialtyId the value for specialty.specialtyId
     *
     * @mbggenerated
     */
    public void setSpecialtyId(Integer specialtyId) {
        this.specialtyId = specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialtyName
     *
     * @return the value of specialty.specialtyName
     *
     * @mbggenerated
     */
    public String getSpecialtyName() {
        return specialtyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialtyName
     *
     * @param specialtyName the value for specialty.specialtyName
     *
     * @mbggenerated
     */
    public void setSpecialtyName(String specialtyName) {
        this.specialtyName = specialtyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.department_departmentId
     *
     * @return the value of specialty.department_departmentId
     *
     * @mbggenerated
     */
    public Integer getDepartment_departmentId() {
        return department_departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.department_departmentId
     *
     * @param department_departmentId the value for specialty.department_departmentId
     *
     * @mbggenerated
     */
    public void setDepartment_departmentId(Integer department_departmentId) {
        this.department_departmentId = department_departmentId;
    }
}