package com.paly.domain;

import java.io.Serializable;
import java.util.List;

/**
 * 专业
 * @author linyu
 *
 */
public class Specialty implements Serializable {
   
	private static final long serialVersionUID = 8032169560857196948L;
	
    private Integer specialtyId;

    /**
     * 专业名
     */
    private String specialtyName;

    /**
     * 属于哪个与院系
     */
    private Department department;
    
    /**
     * 拥有多个班级
     */
    private List<Classes> classes;

    
    public Specialty() {
		super();
	}
    
    /**
     * 带参实例化专业实体
     * @param specialtyName 专业名称，不能为null
     * @param department 所属院系，不为空
     */
    public Specialty(String specialtyName, Department department) {
		super();
		this.specialtyName = specialtyName;
		this.department = department;
	}

	

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialtyId
     *
     * @return the value of specialty.specialtyId
     *
     * @mbggenerated
     */
    public Integer getSpecialtyId() {
        return specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialtyId
     *
     * @param specialtyId the value for specialty.specialtyId
     *
     * @mbggenerated
     */
    public void setSpecialtyId(Integer specialtyId) {
        this.specialtyId = specialtyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column specialty.specialtyName
     *
     * @return the value of specialty.specialtyName
     *
     * @mbggenerated
     */
    public String getSpecialtyName() {
        return specialtyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column specialty.specialtyName
     *
     * @param specialtyName the value for specialty.specialtyName
     *
     * @mbggenerated
     */
    public void setSpecialtyName(String specialtyName) {
        this.specialtyName = specialtyName;
    }

	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public List<Classes> getClasses() {
		return classes;
	}

	public void setClasses(List<Classes> classes) {
		this.classes = classes;
	}
}