package com.paly.domain;

import java.io.Serializable;

/**
 * 学生
 * @author linyu
 *
 */
public class Student implements Serializable {
    
	private static final long serialVersionUID = 8991811301801914147L;

    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentNumber
     *
     * @mbggenerated
     */
    private String studentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentName
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentSex
     *
     * @mbggenerated
     */
    private String studentSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentEmail
     *
     * @mbggenerated
     */
    private String studentEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.user_userId
     *
     * @mbggenerated
     */
    private Integer user_userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classes_classesId
     *
     * @mbggenerated
     */
    private Integer classes_classesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentId
     *
     * @return the value of student.studentId
     *
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentId
     *
     * @param studentId the value for student.studentId
     *
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentNumber
     *
     * @return the value of student.studentNumber
     *
     * @mbggenerated
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentNumber
     *
     * @param studentNumber the value for student.studentNumber
     *
     * @mbggenerated
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentName
     *
     * @return the value of student.studentName
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentName
     *
     * @param studentName the value for student.studentName
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentSex
     *
     * @return the value of student.studentSex
     *
     * @mbggenerated
     */
    public String getStudentSex() {
        return studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentSex
     *
     * @param studentSex the value for student.studentSex
     *
     * @mbggenerated
     */
    public void setStudentSex(String studentSex) {
        this.studentSex = studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentEmail
     *
     * @return the value of student.studentEmail
     *
     * @mbggenerated
     */
    public String getStudentEmail() {
        return studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentEmail
     *
     * @param studentEmail the value for student.studentEmail
     *
     * @mbggenerated
     */
    public void setStudentEmail(String studentEmail) {
        this.studentEmail = studentEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.user_userId
     *
     * @return the value of student.user_userId
     *
     * @mbggenerated
     */
    public Integer getUser_userId() {
        return user_userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.user_userId
     *
     * @param user_userId the value for student.user_userId
     *
     * @mbggenerated
     */
    public void setUser_userId(Integer user_userId) {
        this.user_userId = user_userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classes_classesId
     *
     * @return the value of student.classes_classesId
     *
     * @mbggenerated
     */
    public Integer getClasses_classesId() {
        return classes_classesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classes_classesId
     *
     * @param classes_classesId the value for student.classes_classesId
     *
     * @mbggenerated
     */
    public void setClasses_classesId(Integer classes_classesId) {
        this.classes_classesId = classes_classesId;
    }
}