package com.paly.domain;

import java.io.Serializable;

/**
 * 学习进度
 * @author linyu
 *
 */
public class Studyschedule implements Serializable {
    
	private static final long serialVersionUID = -3009764170511857076L;

    private Integer studyscheduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyschedule.studyscheduleHasNum
     *
     * @mbggenerated
     */
    private String studyscheduleHasNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyschedule.subsection_subsectionId
     *
     * @mbggenerated
     */
    private Integer subsection_subsectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studyschedule.student_studentId
     *
     * @mbggenerated
     */
    private Integer student_studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyschedule.studyscheduleId
     *
     * @return the value of studyschedule.studyscheduleId
     *
     * @mbggenerated
     */
    public Integer getStudyscheduleId() {
        return studyscheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyschedule.studyscheduleId
     *
     * @param studyscheduleId the value for studyschedule.studyscheduleId
     *
     * @mbggenerated
     */
    public void setStudyscheduleId(Integer studyscheduleId) {
        this.studyscheduleId = studyscheduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyschedule.studyscheduleHasNum
     *
     * @return the value of studyschedule.studyscheduleHasNum
     *
     * @mbggenerated
     */
    public String getStudyscheduleHasNum() {
        return studyscheduleHasNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyschedule.studyscheduleHasNum
     *
     * @param studyscheduleHasNum the value for studyschedule.studyscheduleHasNum
     *
     * @mbggenerated
     */
    public void setStudyscheduleHasNum(String studyscheduleHasNum) {
        this.studyscheduleHasNum = studyscheduleHasNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyschedule.subsection_subsectionId
     *
     * @return the value of studyschedule.subsection_subsectionId
     *
     * @mbggenerated
     */
    public Integer getSubsection_subsectionId() {
        return subsection_subsectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyschedule.subsection_subsectionId
     *
     * @param subsection_subsectionId the value for studyschedule.subsection_subsectionId
     *
     * @mbggenerated
     */
    public void setSubsection_subsectionId(Integer subsection_subsectionId) {
        this.subsection_subsectionId = subsection_subsectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studyschedule.student_studentId
     *
     * @return the value of studyschedule.student_studentId
     *
     * @mbggenerated
     */
    public Integer getStudent_studentId() {
        return student_studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studyschedule.student_studentId
     *
     * @param student_studentId the value for studyschedule.student_studentId
     *
     * @mbggenerated
     */
    public void setStudent_studentId(Integer student_studentId) {
        this.student_studentId = student_studentId;
    }
}