package com.paly.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * 子章节
 * @author linyu
 *
 */
public class Subsection implements Serializable{
   
	private static final long serialVersionUID = 824814283958151371L;

	
    private Integer subsectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subsection.subsectionName
     *
     * @mbggenerated
     */
    private String subsectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subsection.subsectionTime
     *
     * @mbggenerated
     */
    private Date subsectionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subsection.subsectionChecked
     *
     * @mbggenerated
     */
    private Boolean subsectionChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subsection.section_sectionId
     *
     * @mbggenerated
     */
    private Integer section_sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subsection.subsectionContent
     *
     * @mbggenerated
     */
    private String subsectionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subsection.subsectionId
     *
     * @return the value of subsection.subsectionId
     *
     * @mbggenerated
     */
    public Integer getSubsectionId() {
        return subsectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subsection.subsectionId
     *
     * @param subsectionId the value for subsection.subsectionId
     *
     * @mbggenerated
     */
    public void setSubsectionId(Integer subsectionId) {
        this.subsectionId = subsectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subsection.subsectionName
     *
     * @return the value of subsection.subsectionName
     *
     * @mbggenerated
     */
    public String getSubsectionName() {
        return subsectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subsection.subsectionName
     *
     * @param subsectionName the value for subsection.subsectionName
     *
     * @mbggenerated
     */
    public void setSubsectionName(String subsectionName) {
        this.subsectionName = subsectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subsection.subsectionTime
     *
     * @return the value of subsection.subsectionTime
     *
     * @mbggenerated
     */
    public Date getSubsectionTime() {
        return subsectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subsection.subsectionTime
     *
     * @param subsectionTime the value for subsection.subsectionTime
     *
     * @mbggenerated
     */
    public void setSubsectionTime(Date subsectionTime) {
        this.subsectionTime = subsectionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subsection.subsectionChecked
     *
     * @return the value of subsection.subsectionChecked
     *
     * @mbggenerated
     */
    public Boolean getSubsectionChecked() {
        return subsectionChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subsection.subsectionChecked
     *
     * @param subsectionChecked the value for subsection.subsectionChecked
     *
     * @mbggenerated
     */
    public void setSubsectionChecked(Boolean subsectionChecked) {
        this.subsectionChecked = subsectionChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subsection.section_sectionId
     *
     * @return the value of subsection.section_sectionId
     *
     * @mbggenerated
     */
    public Integer getSection_sectionId() {
        return section_sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subsection.section_sectionId
     *
     * @param section_sectionId the value for subsection.section_sectionId
     *
     * @mbggenerated
     */
    public void setSection_sectionId(Integer section_sectionId) {
        this.section_sectionId = section_sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subsection.subsectionContent
     *
     * @return the value of subsection.subsectionContent
     *
     * @mbggenerated
     */
    public String getSubsectionContent() {
        return subsectionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subsection.subsectionContent
     *
     * @param subsectionContent the value for subsection.subsectionContent
     *
     * @mbggenerated
     */
    public void setSubsectionContent(String subsectionContent) {
        this.subsectionContent = subsectionContent;
    }
}