package com.paly.domain;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userId
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userName
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userPassword
	 * @mbggenerated
	 */
	private String userPassword;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userId
	 * @return  the value of user.userId
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userId
	 * @param userId  the value for user.userId
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userName
	 * @return  the value of user.userName
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userName
	 * @param userName  the value for user.userName
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userPassword
	 * @return  the value of user.userPassword
	 * @mbggenerated
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userPassword
	 * @param userPassword  the value for user.userPassword
	 * @mbggenerated
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}
}